bo-users:
  display-name: ${spring.application.name}

info:
  name: ${bo-users.display-name}
#  version: @project.version@

server:
  port: 7900

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bo-users
