bo-users:
  display-name: bo-users

info:
  name: ${bo-users.display-name}
#  version: @project.version@

server:
  port: 7900

spring:
  data:
    mongodb:
      uri: mongodb://mongo_bo_users:123@localhost:27017/bo-users
